### ISSUE TITLE
running BakeIntoMesh.py results in an error

### ISSUE THREAD

**Issue by ruim** [AyoubKhammassi/UnityBinaryOpacityGrid#1]
When running BakeIntoMesh.py I always get the same error. Tried with the "bicycle" and "gardenvase" samples.
Any help would be appreciated

```
Exporting C:\work\tekuchi\UnityBinaryOpacityGrid\Samples\gardenvase/FullMeshWithFeatures.glb
Traceback (most recent call last):
  File "C:\work\tekuchi\UnityBinaryOpacityGrid\Utility Scripts\BakeIntoMesh.py", line 220, in <module>
    scene.export(exportPath)
  File "C:\Users\ruibm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\trimesh\scene\scene.py", line 958, in export
    return export.export_scene(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ruibm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\trimesh\exchange\export.py", line 262, in export_scene
    data = export_glb(scene, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ruibm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\trimesh\exchange\gltf.py", line 199, in export_glb
    tree, buffer_items = _create_gltf_structure(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ruibm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\trimesh\exchange\gltf.py", line 708, in _create_gltf_structure
    _append_mesh(
TypeError: _append_multi_uv_mesh() got an unexpected keyword argument 'extension_webp'
```

**Comment by AyoubKhammassi** [comment]
Hey, what version of Trimesh are you using? (Make sure it's 3.21.0)

**Comment by ruim** [comment]
this worked, thank you. I was using Trimesh 4.2.2, changing to 3.21.0 solved it
